# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from playbook import entity_pb2 as playbook_dot_entity__pb2


class EntitiesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEntities = channel.unary_unary(
                '/zia.ai.playbook.Entities/ListEntities',
                request_serializer=playbook_dot_entity__pb2.ListEntitiesRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.ListEntitiesResponse.FromString,
                )
        self.GetEntity = channel.unary_unary(
                '/zia.ai.playbook.Entities/GetEntity',
                request_serializer=playbook_dot_entity__pb2.GetEntityRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.GetEntityResponse.FromString,
                )
        self.CreateEntity = channel.unary_unary(
                '/zia.ai.playbook.Entities/CreateEntity',
                request_serializer=playbook_dot_entity__pb2.CreateEntityRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.CreateEntityResponse.FromString,
                )
        self.UpdateEntity = channel.unary_unary(
                '/zia.ai.playbook.Entities/UpdateEntity',
                request_serializer=playbook_dot_entity__pb2.UpdateEntityRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.UpdateEntityResponse.FromString,
                )
        self.DeleteEntity = channel.unary_unary(
                '/zia.ai.playbook.Entities/DeleteEntity',
                request_serializer=playbook_dot_entity__pb2.DeleteEntityRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.DeleteEntityResponse.FromString,
                )
        self.ListSystemEntities = channel.unary_unary(
                '/zia.ai.playbook.Entities/ListSystemEntities',
                request_serializer=playbook_dot_entity__pb2.ListSystemEntitiesRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.ListSystemEntitiesResponse.FromString,
                )
        self.DeleteEntityReferences = channel.unary_unary(
                '/zia.ai.playbook.Entities/DeleteEntityReferences',
                request_serializer=playbook_dot_entity__pb2.DeleteEntityReferencesRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.DeleteEntityReferencesResponse.FromString,
                )
        self.RemapEntityReferences = channel.unary_unary(
                '/zia.ai.playbook.Entities/RemapEntityReferences',
                request_serializer=playbook_dot_entity__pb2.RemapEntityReferencesRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.RemapEntityReferencesResponse.FromString,
                )
        self.GetEntitySettings = channel.unary_unary(
                '/zia.ai.playbook.Entities/GetEntitySettings',
                request_serializer=playbook_dot_entity__pb2.GetEntitySettingsRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.GetEntitySettingsResponse.FromString,
                )
        self.SetEntitySettings = channel.unary_unary(
                '/zia.ai.playbook.Entities/SetEntitySettings',
                request_serializer=playbook_dot_entity__pb2.SetEntitySettingsRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.SetEntitySettingsResponse.FromString,
                )
        self.CreateEntityValue = channel.unary_unary(
                '/zia.ai.playbook.Entities/CreateEntityValue',
                request_serializer=playbook_dot_entity__pb2.CreateEntityValueRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.CreateEntityValueResponse.FromString,
                )
        self.UpdateEntityValue = channel.unary_unary(
                '/zia.ai.playbook.Entities/UpdateEntityValue',
                request_serializer=playbook_dot_entity__pb2.UpdateEntityValueRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.UpdateEntityValueResponse.FromString,
                )
        self.DeleteEntityValue = channel.unary_unary(
                '/zia.ai.playbook.Entities/DeleteEntityValue',
                request_serializer=playbook_dot_entity__pb2.DeleteEntityValueRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.DeleteEntityValueResponse.FromString,
                )
        self.SearchEntityValue = channel.unary_unary(
                '/zia.ai.playbook.Entities/SearchEntityValue',
                request_serializer=playbook_dot_entity__pb2.SearchEntityValueRequest.SerializeToString,
                response_deserializer=playbook_dot_entity__pb2.SearchEntityValueResponse.FromString,
                )


class EntitiesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSystemEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEntityReferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemapEntityReferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntitySettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEntitySettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEntityValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEntityValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEntityValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchEntityValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EntitiesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntities,
                    request_deserializer=playbook_dot_entity__pb2.ListEntitiesRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.ListEntitiesResponse.SerializeToString,
            ),
            'GetEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntity,
                    request_deserializer=playbook_dot_entity__pb2.GetEntityRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.GetEntityResponse.SerializeToString,
            ),
            'CreateEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEntity,
                    request_deserializer=playbook_dot_entity__pb2.CreateEntityRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.CreateEntityResponse.SerializeToString,
            ),
            'UpdateEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEntity,
                    request_deserializer=playbook_dot_entity__pb2.UpdateEntityRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.UpdateEntityResponse.SerializeToString,
            ),
            'DeleteEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEntity,
                    request_deserializer=playbook_dot_entity__pb2.DeleteEntityRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.DeleteEntityResponse.SerializeToString,
            ),
            'ListSystemEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSystemEntities,
                    request_deserializer=playbook_dot_entity__pb2.ListSystemEntitiesRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.ListSystemEntitiesResponse.SerializeToString,
            ),
            'DeleteEntityReferences': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEntityReferences,
                    request_deserializer=playbook_dot_entity__pb2.DeleteEntityReferencesRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.DeleteEntityReferencesResponse.SerializeToString,
            ),
            'RemapEntityReferences': grpc.unary_unary_rpc_method_handler(
                    servicer.RemapEntityReferences,
                    request_deserializer=playbook_dot_entity__pb2.RemapEntityReferencesRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.RemapEntityReferencesResponse.SerializeToString,
            ),
            'GetEntitySettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntitySettings,
                    request_deserializer=playbook_dot_entity__pb2.GetEntitySettingsRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.GetEntitySettingsResponse.SerializeToString,
            ),
            'SetEntitySettings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEntitySettings,
                    request_deserializer=playbook_dot_entity__pb2.SetEntitySettingsRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.SetEntitySettingsResponse.SerializeToString,
            ),
            'CreateEntityValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEntityValue,
                    request_deserializer=playbook_dot_entity__pb2.CreateEntityValueRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.CreateEntityValueResponse.SerializeToString,
            ),
            'UpdateEntityValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEntityValue,
                    request_deserializer=playbook_dot_entity__pb2.UpdateEntityValueRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.UpdateEntityValueResponse.SerializeToString,
            ),
            'DeleteEntityValue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEntityValue,
                    request_deserializer=playbook_dot_entity__pb2.DeleteEntityValueRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.DeleteEntityValueResponse.SerializeToString,
            ),
            'SearchEntityValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEntityValue,
                    request_deserializer=playbook_dot_entity__pb2.SearchEntityValueRequest.FromString,
                    response_serializer=playbook_dot_entity__pb2.SearchEntityValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zia.ai.playbook.Entities', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Entities(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/ListEntities',
            playbook_dot_entity__pb2.ListEntitiesRequest.SerializeToString,
            playbook_dot_entity__pb2.ListEntitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/GetEntity',
            playbook_dot_entity__pb2.GetEntityRequest.SerializeToString,
            playbook_dot_entity__pb2.GetEntityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/CreateEntity',
            playbook_dot_entity__pb2.CreateEntityRequest.SerializeToString,
            playbook_dot_entity__pb2.CreateEntityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/UpdateEntity',
            playbook_dot_entity__pb2.UpdateEntityRequest.SerializeToString,
            playbook_dot_entity__pb2.UpdateEntityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/DeleteEntity',
            playbook_dot_entity__pb2.DeleteEntityRequest.SerializeToString,
            playbook_dot_entity__pb2.DeleteEntityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSystemEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/ListSystemEntities',
            playbook_dot_entity__pb2.ListSystemEntitiesRequest.SerializeToString,
            playbook_dot_entity__pb2.ListSystemEntitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEntityReferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/DeleteEntityReferences',
            playbook_dot_entity__pb2.DeleteEntityReferencesRequest.SerializeToString,
            playbook_dot_entity__pb2.DeleteEntityReferencesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemapEntityReferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/RemapEntityReferences',
            playbook_dot_entity__pb2.RemapEntityReferencesRequest.SerializeToString,
            playbook_dot_entity__pb2.RemapEntityReferencesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEntitySettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/GetEntitySettings',
            playbook_dot_entity__pb2.GetEntitySettingsRequest.SerializeToString,
            playbook_dot_entity__pb2.GetEntitySettingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetEntitySettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/SetEntitySettings',
            playbook_dot_entity__pb2.SetEntitySettingsRequest.SerializeToString,
            playbook_dot_entity__pb2.SetEntitySettingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEntityValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/CreateEntityValue',
            playbook_dot_entity__pb2.CreateEntityValueRequest.SerializeToString,
            playbook_dot_entity__pb2.CreateEntityValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEntityValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/UpdateEntityValue',
            playbook_dot_entity__pb2.UpdateEntityValueRequest.SerializeToString,
            playbook_dot_entity__pb2.UpdateEntityValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEntityValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/DeleteEntityValue',
            playbook_dot_entity__pb2.DeleteEntityValueRequest.SerializeToString,
            playbook_dot_entity__pb2.DeleteEntityValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchEntityValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.Entities/SearchEntityValue',
            playbook_dot_entity__pb2.SearchEntityValueRequest.SerializeToString,
            playbook_dot_entity__pb2.SearchEntityValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
