# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tags import tags_pb2 as tags_dot_tags__pb2


class TagsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTag = channel.unary_unary(
                '/zia.ai.tags.Tags/CreateTag',
                request_serializer=tags_dot_tags__pb2.CreateTagRequest.SerializeToString,
                response_deserializer=tags_dot_tags__pb2.CreateTagResponse.FromString,
                )
        self.ListTags = channel.unary_unary(
                '/zia.ai.tags.Tags/ListTags',
                request_serializer=tags_dot_tags__pb2.ListTagsRequest.SerializeToString,
                response_deserializer=tags_dot_tags__pb2.ListTagsResponse.FromString,
                )
        self.UpdateTag = channel.unary_unary(
                '/zia.ai.tags.Tags/UpdateTag',
                request_serializer=tags_dot_tags__pb2.UpdateTagRequest.SerializeToString,
                response_deserializer=tags_dot_tags__pb2.UpdateTagResponse.FromString,
                )
        self.DeleteTag = channel.unary_unary(
                '/zia.ai.tags.Tags/DeleteTag',
                request_serializer=tags_dot_tags__pb2.DeleteTagRequest.SerializeToString,
                response_deserializer=tags_dot_tags__pb2.DeleteTagResponse.FromString,
                )


class TagsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TagsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTag': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTag,
                    request_deserializer=tags_dot_tags__pb2.CreateTagRequest.FromString,
                    response_serializer=tags_dot_tags__pb2.CreateTagResponse.SerializeToString,
            ),
            'ListTags': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTags,
                    request_deserializer=tags_dot_tags__pb2.ListTagsRequest.FromString,
                    response_serializer=tags_dot_tags__pb2.ListTagsResponse.SerializeToString,
            ),
            'UpdateTag': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTag,
                    request_deserializer=tags_dot_tags__pb2.UpdateTagRequest.FromString,
                    response_serializer=tags_dot_tags__pb2.UpdateTagResponse.SerializeToString,
            ),
            'DeleteTag': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTag,
                    request_deserializer=tags_dot_tags__pb2.DeleteTagRequest.FromString,
                    response_serializer=tags_dot_tags__pb2.DeleteTagResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zia.ai.tags.Tags', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tags(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.tags.Tags/CreateTag',
            tags_dot_tags__pb2.CreateTagRequest.SerializeToString,
            tags_dot_tags__pb2.CreateTagResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.tags.Tags/ListTags',
            tags_dot_tags__pb2.ListTagsRequest.SerializeToString,
            tags_dot_tags__pb2.ListTagsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.tags.Tags/UpdateTag',
            tags_dot_tags__pb2.UpdateTagRequest.SerializeToString,
            tags_dot_tags__pb2.UpdateTagResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.tags.Tags/DeleteTag',
            tags_dot_tags__pb2.DeleteTagRequest.SerializeToString,
            tags_dot_tags__pb2.DeleteTagResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
