# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: longrunning/v1alpha1/operations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%longrunning/v1alpha1/operations.proto\x12\x1bzia.ai.longrunning.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\"C\n\x13GetOperationRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05\x61wait\x18\x03 \x01(\x08\"Q\n\x14GetOperationResponse\x12\x39\n\toperation\x18\x01 \x01(\x0b\x32&.zia.ai.longrunning.v1alpha1.Operation\"\xa1\x01\n\tOperation\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12\x33\n\x05\x65rror\x18\x04 \x01(\x0b\x32\".zia.ai.longrunning.v1alpha1.ErrorH\x00\x12(\n\x08response\x18\x05 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x42\x08\n\x06result\"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb1\x01\n\nOperations\x12\xa2\x01\n\x0cGetOperation\x12\x30.zia.ai.longrunning.v1alpha1.GetOperationRequest\x1a\x31.zia.ai.longrunning.v1alpha1.GetOperationResponse\"-\x82\xd3\xe4\x93\x02\'\x12%/v1alpha1/operations/{namespace}/{id}BGZEgithub.com/zia-ai/platform/pkg/api/longrunning/v1alpha1;pblongrunningb\x06proto3')



_GETOPERATIONREQUEST = DESCRIPTOR.message_types_by_name['GetOperationRequest']
_GETOPERATIONRESPONSE = DESCRIPTOR.message_types_by_name['GetOperationResponse']
_OPERATION = DESCRIPTOR.message_types_by_name['Operation']
_ERROR = DESCRIPTOR.message_types_by_name['Error']
GetOperationRequest = _reflection.GeneratedProtocolMessageType('GetOperationRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETOPERATIONREQUEST,
  '__module__' : 'longrunning.v1alpha1.operations_pb2'
  # @@protoc_insertion_point(class_scope:zia.ai.longrunning.v1alpha1.GetOperationRequest)
  })
_sym_db.RegisterMessage(GetOperationRequest)

GetOperationResponse = _reflection.GeneratedProtocolMessageType('GetOperationResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETOPERATIONRESPONSE,
  '__module__' : 'longrunning.v1alpha1.operations_pb2'
  # @@protoc_insertion_point(class_scope:zia.ai.longrunning.v1alpha1.GetOperationResponse)
  })
_sym_db.RegisterMessage(GetOperationResponse)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'longrunning.v1alpha1.operations_pb2'
  # @@protoc_insertion_point(class_scope:zia.ai.longrunning.v1alpha1.Operation)
  })
_sym_db.RegisterMessage(Operation)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'longrunning.v1alpha1.operations_pb2'
  # @@protoc_insertion_point(class_scope:zia.ai.longrunning.v1alpha1.Error)
  })
_sym_db.RegisterMessage(Error)

_OPERATIONS = DESCRIPTOR.services_by_name['Operations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZEgithub.com/zia-ai/platform/pkg/api/longrunning/v1alpha1;pblongrunning'
  _OPERATIONS.methods_by_name['GetOperation']._options = None
  _OPERATIONS.methods_by_name['GetOperation']._serialized_options = b'\202\323\344\223\002\'\022%/v1alpha1/operations/{namespace}/{id}'
  _GETOPERATIONREQUEST._serialized_start=127
  _GETOPERATIONREQUEST._serialized_end=194
  _GETOPERATIONRESPONSE._serialized_start=196
  _GETOPERATIONRESPONSE._serialized_end=277
  _OPERATION._serialized_start=280
  _OPERATION._serialized_end=441
  _ERROR._serialized_start=443
  _ERROR._serialized_end=481
  _OPERATIONS._serialized_start=484
  _OPERATIONS._serialized_end=661
# @@protoc_insertion_point(module_scope)
