"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class GetOperationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    AWAIT_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    """Namespace in which the operation was launched."""
    id: builtins.str
    """Unique identifier of the operation."""
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["await", b"await", "id", b"id", "namespace", b"namespace"]) -> None: ...

global___GetOperationRequest = GetOperationRequest

class GetOperationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_FIELD_NUMBER: builtins.int
    @property
    def operation(self) -> global___Operation: ...
    def __init__(
        self,
        *,
        operation: global___Operation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["operation", b"operation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["operation", b"operation"]) -> None: ...

global___GetOperationResponse = GetOperationResponse

class Operation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    DONE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    """Namespace in which the operation was launched."""
    id: builtins.str
    """Unique identifier of the operation."""
    done: builtins.bool
    """Indicates that the operation has completed.
    If `error` is set, the operation has failed.
    Otherwise, the operation has succeeded and `result` may be set if the operation has a response.
    """
    @property
    def error(self) -> global___Error: ...
    @property
    def response(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        id: builtins.str = ...,
        done: builtins.bool = ...,
        error: global___Error | None = ...,
        response: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error", b"error", "response", b"response", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["done", b"done", "error", b"error", "id", b"id", "namespace", b"namespace", "response", b"response", "result", b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["result", b"result"]) -> typing_extensions.Literal["error", "response"] | None: ...

global___Operation = Operation

class Error(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    code: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        code: builtins.int = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "message", b"message"]) -> None: ...

global___Error = Error
