# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.api import httpbody_pb2 as google_dot_api_dot_httpbody__pb2
from playbook.data.v1alpha1 import data_pb2 as playbook_dot_data_dot_v1alpha1_dot_data__pb2


class DataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExportIntents = channel.unary_unary(
                '/zia.ai.playbook.data.v1alpha1.Data/ExportIntents',
                request_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ExportIntentsRequest.SerializeToString,
                response_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ExportIntentsResponse.FromString,
                )
        self.ExportIntentsHttp = channel.unary_unary(
                '/zia.ai.playbook.data.v1alpha1.Data/ExportIntentsHttp',
                request_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ExportIntentsRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
                )
        self.ImportIntents = channel.unary_unary(
                '/zia.ai.playbook.data.v1alpha1.Data/ImportIntents',
                request_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsRequest.SerializeToString,
                response_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsResponse.FromString,
                )
        self.ImportIntentsHttp = channel.unary_unary(
                '/zia.ai.playbook.data.v1alpha1.Data/ImportIntentsHttp',
                request_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsRequest.SerializeToString,
                response_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsResponse.FromString,
                )
        self.ImportConversationsFile = channel.unary_unary(
                '/zia.ai.playbook.data.v1alpha1.Data/ImportConversationsFile',
                request_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportConversationsFileRequest.SerializeToString,
                response_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportConversationsFileResponse.FromString,
                )
        self.ListConversationsFile = channel.unary_unary(
                '/zia.ai.playbook.data.v1alpha1.Data/ListConversationsFile',
                request_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ListConversationsFileRequest.SerializeToString,
                response_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ListConversationsFileResponse.FromString,
                )
        self.DeleteConversationsFile = channel.unary_unary(
                '/zia.ai.playbook.data.v1alpha1.Data/DeleteConversationsFile',
                request_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.DeleteConversationsFileRequest.SerializeToString,
                response_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.DeleteConversationsFileResponse.FromString,
                )


class DataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExportIntents(self, request, context):
        """Exports intents of a workspace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportIntentsHttp(self, request, context):
        """Exports intents of a workspace.
        @openapi_private
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportIntents(self, request, context):
        """Imports intents into a workspace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportIntentsHttp(self, request, context):
        """Import intents into a workspace using a multipart request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportConversationsFile(self, request, context):
        """Import unlabelled conversational files into a conversation source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversationsFile(self, request, context):
        """Lists unlabelled conversational files of a conversation source.
        @openapi_private
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversationsFile(self, request, context):
        """Delete an unlabelled conversational file from a conversation source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExportIntents': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportIntents,
                    request_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ExportIntentsRequest.FromString,
                    response_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ExportIntentsResponse.SerializeToString,
            ),
            'ExportIntentsHttp': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportIntentsHttp,
                    request_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ExportIntentsRequest.FromString,
                    response_serializer=google_dot_api_dot_httpbody__pb2.HttpBody.SerializeToString,
            ),
            'ImportIntents': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportIntents,
                    request_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsRequest.FromString,
                    response_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsResponse.SerializeToString,
            ),
            'ImportIntentsHttp': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportIntentsHttp,
                    request_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsRequest.FromString,
                    response_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsResponse.SerializeToString,
            ),
            'ImportConversationsFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportConversationsFile,
                    request_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportConversationsFileRequest.FromString,
                    response_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportConversationsFileResponse.SerializeToString,
            ),
            'ListConversationsFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversationsFile,
                    request_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ListConversationsFileRequest.FromString,
                    response_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.ListConversationsFileResponse.SerializeToString,
            ),
            'DeleteConversationsFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversationsFile,
                    request_deserializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.DeleteConversationsFileRequest.FromString,
                    response_serializer=playbook_dot_data_dot_v1alpha1_dot_data__pb2.DeleteConversationsFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zia.ai.playbook.data.v1alpha1.Data', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Data(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExportIntents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.data.v1alpha1.Data/ExportIntents',
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ExportIntentsRequest.SerializeToString,
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ExportIntentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExportIntentsHttp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.data.v1alpha1.Data/ExportIntentsHttp',
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ExportIntentsRequest.SerializeToString,
            google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportIntents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.data.v1alpha1.Data/ImportIntents',
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsRequest.SerializeToString,
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportIntentsHttp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.data.v1alpha1.Data/ImportIntentsHttp',
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsRequest.SerializeToString,
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportIntentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportConversationsFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.data.v1alpha1.Data/ImportConversationsFile',
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportConversationsFileRequest.SerializeToString,
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ImportConversationsFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListConversationsFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.data.v1alpha1.Data/ListConversationsFile',
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ListConversationsFileRequest.SerializeToString,
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.ListConversationsFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteConversationsFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zia.ai.playbook.data.v1alpha1.Data/DeleteConversationsFile',
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.DeleteConversationsFileRequest.SerializeToString,
            playbook_dot_data_dot_v1alpha1_dot_data__pb2.DeleteConversationsFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
